#!/bin/bash
# /etc/init.d/go-e-sma-homewizard-controller
# 
# System startup script for go-e-sma-homewizard-controller (LSB compliant init script)
# This script is for systems without systemd support (Debian Jessie and older)

### BEGIN INIT INFO
# Provides:          go-e-sma-homewizard-controller
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: go-e-charger SMA HomeWizard Load Manager
# Description:       Linux bash script to manage go-e-charger with load management
#                    and PV integration
### END INIT INFO

set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/go-e-sma-homewizard-controller
NAME=go-e-sma-homewizard-controller
DESC="go-e-charger SMA HomeWizard Load Manager"
PIDFILE=/var/run/$NAME.pid

# Load LSB init functions
. /lib/lsb/init-functions

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

case "$1" in
    start)
        log_daemon_msg "Starting $DESC" "$NAME"
        
        # Check if already running
        if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE") 2>/dev/null; then
            log_progress_msg "already running"
            log_end_msg 0
            exit 0
        fi
        
        # Start the daemon
        start_daemon -p "$PIDFILE" "$DAEMON" >> /var/log/$NAME/$NAME.log 2>&1 &
        RETVAL=$?
        
        # Save PID
        echo $! > "$PIDFILE"
        
        log_end_msg $RETVAL
        ;;
    
    stop)
        log_daemon_msg "Stopping $DESC" "$NAME"
        
        if [ -f "$PIDFILE" ]; then
            PID=$(cat "$PIDFILE")
            if kill -0 "$PID" 2>/dev/null; then
                kill -TERM "$PID"
                
                # Wait for process to terminate
                for i in $(seq 1 10); do
                    sleep 1
                    if ! kill -0 "$PID" 2>/dev/null; then
                        break
                    fi
                done
                
                # Force kill if still running
                if kill -0 "$PID" 2>/dev/null; then
                    kill -9 "$PID" || true
                fi
            fi
            rm -f "$PIDFILE"
            log_end_msg 0
        else
            log_end_msg 1
        fi
        ;;
    
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    
    status)
        if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE") 2>/dev/null; then
            log_success_msg "$NAME is running (PID: $(cat $PIDFILE))"
            exit 0
        else
            log_failure_msg "$NAME is not running"
            exit 3
        fi
        ;;
    
    force-reload)
        $0 restart
        ;;
    
    *)
        echo "Usage: $0 {start|stop|restart|force-reload|status}"
        exit 1
        ;;
esac

exit 0
